version: '2'

services:
  dev.earvinkayonga.com:
    image: drone/drone:0.5
    ports:
      - 8000:8000
    volumes:
      - ./drone:/var/lib/drone/
      - /etc/letsencrypt/live/dev.earvinkayonga.com/fullchain.pem:/certs/fullchain.pem:ro
      - /etc/letsencrypt/live/dev.earvinkayonga.com/privkey.pem:/certs/privkey.pem:ro
    restart: always
    environment:
      - DRONE_OPEN=true
      - DRONE_GITHUB=true
      - DRONE_GITHUB_CONTEXT=continuous-integration/drone
      - DRONE_GITHUB_PRIVATE_MODE=true
      - DRONE_GITHUB_MERGE_REF=true
      - DRONE_CACHE_TTY=1m
      - DRONE_SERVER_CERT=${DRONE_SERVER_CERT}
      - DRONE_SERVER_KEY=${DRONE_SERVER_KEY}
      - DRONE_GITHUB_CLIENT=${DRONE_GITHUB_CLIENT}
      - DRONE_GITHUB_SECRET=${DRONE_GITHUB_SECRET}
      - DRONE_SECRET=${DRONE_SECRET}
      - DRONE_ADMIN=${DRONE_ADMIN}

  drone-agent1:
    image: drone/drone:0.5
    command: agent
    restart: always
    depends_on: [ dev.earvinkayonga.com ]
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DRONE_SERVER=wss://dev.earvinkayonga.com:8000/ws/broker
      - DRONE_SECRET=${DRONE_SECRET}

  drone-agent2:
    image: drone/drone:0.5
    command: agent
    restart: always
    depends_on: [ dev.earvinkayonga.com ]
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DRONE_SERVER=wss://dev.earvinkayonga.com:8000/ws/broker
      - DRONE_SECRET=${DRONE_SECRET}
